### ISSUE TITLE
Image in Part 2 (Make and commit changes) in version 1 of exercise 1 is incorrect.

### ISSUE THREAD

**Issue by jpratt-mru** [MRU-F22-CS1/instructions#1]
Just had a student ping me on this! The current screenshot:
![image](https://user-images.githubusercontent.com/29438487/190296928-46c05a05-de1b-4480-bf42-2eb7ade7c38b.png)

is incorrect for version 1, since they WON'T be modding the README, but will instead modding `starter.txt`.

I apologize for not fixing this myself, but I'm putting out a few evening fires at work here right now!

**Comment by jpratt-mru** [comment]
Before I forget: I will be recommending to my students that they WATCH (All Activity) this instructions repo; that way, they'll receive email notifications if we decide to make issues when changes are made in here. I think that'd be useful, though I'm not sure whether "changing the docs" is the industry way of doing this sort of thing!

**Comment by cfcurtis** [comment]
I see they missed the preceding line that says "it is not necessarily named README" :wink:. I was being lazy and used the screenshots from last semester, so you'll notice it says "join the class of Winter 2022". That said, there are a number of places where I refer to a ".md" file because I thought that's what we were using, but I will change them to .txt.

I have a preference for keeping issues as issues, but I see the appeal in a centralized notification. If we pushed changes as PRs then notifications would go out, but that's another thing to remember to do. I'll try it out for this one and see how it goes.

While we're on the topic of watching, I highly recommend everyone disable "automatically watch repositories" by clicking on your profile in the top right, then going to Settings -> Notifications. This prevents getting an email every time a student makes a change to a repo.
![Screenshot from 2022-09-14 20-42-30](https://user-images.githubusercontent.com/282731/190303314-d4cba3cb-bda6-469a-91da-7cc54487c41d.png)
